#!/bin/bash
configFile=~/.config/i3/config
echo "##### DO NOT EDIT THIS FILE #####" > $configFile
echo -e "##### Edit files in conf.d/ and run generateConfig.sh or press mod+shift+c to generate this file ####\n" >> $configFile
cat ~/.config/i3/config.d/* >> $configFile
